#!/usr/bin/env node
/* Generated by project-setup. Advisory quality report (NOT a gate).
 * Run the "report" package.json script -> quality-report.md + quality-report.json */
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { join } from 'node:path';

const require = createRequire(import.meta.url);

export function gradeFor(score) {
  const s = typeof score === 'number' ? score : 0;
  return s >= 90 ? 'A' : s >= 80 ? 'B' : s >= 70 ? 'C' : s >= 60 ? 'D' : 'F';
}

// Pure projection of fallow's JSON (schema_version 7 / fallow 2.91) into the
// report's data shape. Kept separate from main() so it can be tested against
// real-shaped fallow output without fallow installed. fallow `health` exposes
// the score under `health_score`, per-function complexity under `findings`, and
// prioritized fixes under `targets` — there is NO `hotspots` key.
export function extractData({ healthJson = {}, deadJson = {}, dupesJson = {}, coverageSummary = null } = {}) {
  const hs = healthJson.health_score ?? {};
  const summary = healthJson.summary ?? {};
  const hasScore = typeof hs.score === 'number';
  const findings = Array.isArray(healthJson.findings) ? healthJson.findings : [];
  const hotspots = findings
    .filter((f) => f && (f.severity === 'critical' || f.severity === 'high'))
    .sort((a, b) => (b.crap ?? 0) - (a.crap ?? 0))
    .slice(0, 5)
    .map((f) => ({ name: f.name ?? '(anonymous)', file: f.path ?? f.file ?? '?', crap: f.crap ?? 0, severity: f.severity }));
  const targets = (Array.isArray(healthJson.targets) ? healthJson.targets : [])
    .filter((t) => t && typeof t.recommendation === 'string')
    .slice(0, 3);
  const pct = coverageSummary?.total?.lines?.pct;
  return {
    health: {
      score: hasScore ? hs.score : null,
      grade: hasScore ? (hs.grade ?? gradeFor(hs.score)) : null,
      criticalCount: summary.severity_critical_count ?? hotspots.filter((h) => h.severity === 'critical').length,
      hotspots,
    },
    deadCode: deadJson.summary ?? { total_issues: 0 },
    dupes: dupesJson.stats ?? { clone_groups: 0 },
    lintWarnings: { total: 0, byRule: {} }, // populated by eslint -f json in a follow-up; advisory
    locHotspots: [],
    coverage: { lines: typeof pct === 'number' ? Math.floor(pct) : null },
    targets,
  };
}

export function buildReport(d, runCmd = 'npm run') {
  const actions = [];
  // Complexity hotspots first — fallow's richest, most actionable signal.
  for (const h of d.health.hotspots ?? []) actions.push(`Refactor complexity hotspot ${h.name} (${h.file}, CRAP ${h.crap}).`);
  if (d.deadCode.total_issues > 0) actions.push(`Remove ${d.deadCode.total_issues} dead-code finding(s) (${runCmd} quality:dead-code).`);
  if (d.dupes.clone_groups > 0) actions.push(`Dedupe ${d.dupes.clone_groups} clone group(s) (${runCmd} quality:dupes).`);
  if (typeof d.coverage.lines === 'number' && d.coverage.lines < 80) actions.push(`Raise test coverage — currently ${d.coverage.lines}% lines (target 80%).`);
  for (const t of d.targets ?? []) actions.push(t.recommendation);
  for (const [rule, n] of Object.entries(d.lintWarnings.byRule)) actions.push(`Burn down ${n}x lint warn: ${rule} (then promote to error).`);
  for (const h of d.locHotspots) actions.push(`Split oversized file ${h.file} (${h.loc} LOC).`);

  // Never fabricate "Grade F / 0%" on a fresh repo with nothing to score — that
  // reads as a failure right next to "the harness is green".
  const healthCell = d.health.score == null
    ? 'n/a (new project — nothing to score yet)'
    : `${d.health.score} (Grade ${d.health.grade})`;
  const coverageCell = d.coverage.lines == null ? 'no tests yet' : `${d.coverage.lines}% lines`;

  const lines = [
    '# Quality report',
    '',
    `**Health:** ${healthCell} | **Coverage:** ${coverageCell}`,
    `**Dead code:** ${d.deadCode.total_issues} | **Clone groups:** ${d.dupes.clone_groups} | **Lint warnings:** ${d.lintWarnings.total}`,
    '',
    '## Act on this next',
    '',
    actions.length ? actions.map((a, i) => `${i + 1}. ${a}`).join('\n') : '_No action items — the harness is green._',
    '',
  ];
  return { markdown: lines.join('\n'), json: { ...d, actions } };
}

// Resolve fallow from node_modules (NOT `npx`, which can hit the network or miss
// a yarn-PnP/non-npm layout) and run it with the current node. fallow exits
// non-zero when it has findings — that is still a complete JSON report — but a
// missing/broken fallow yields no JSON, and we must NOT turn that into a green
// "no action items" report. So: parse stdout if present, otherwise throw.
function runFallow(sub) {
  let bin;
  try {
    bin = require.resolve('fallow/bin/fallow');
  } catch {
    throw new Error('fallow is not installed — run your package manager install, then `report` again.');
  }
  let stdout;
  try {
    stdout = execFileSync(process.execPath, [bin, ...sub, '--quiet', '--format', 'json'], {
      encoding: 'utf8',
      maxBuffer: 256 * 1024 * 1024,
      stdio: ['ignore', 'pipe', 'ignore'],
    });
  } catch (e) {
    stdout = e.stdout; // non-zero exit on findings; the JSON report is on stdout
  }
  if (!stdout || !stdout.trim()) throw new Error(`fallow ${sub.join(' ')} produced no output.`);
  try {
    return JSON.parse(stdout);
  } catch {
    throw new Error(`fallow ${sub.join(' ')} did not return JSON.`);
  }
}

// The report is copied verbatim into the target, so it cannot be rendered with
// the package manager at generation time — detect it at runtime instead, so the
// action commands it prints are correct on pnpm/yarn/bun, not just npm.
export function detectRunCmd(cwd = process.cwd()) {
  let pm = 'npm';
  try {
    const declared = JSON.parse(readFileSync(join(cwd, 'package.json'), 'utf8')).packageManager;
    if (typeof declared === 'string') pm = declared.split('@')[0];
  } catch {
    /* no package.json field */
  }
  if (pm === 'npm') {
    if (existsSync(join(cwd, 'pnpm-lock.yaml'))) pm = 'pnpm';
    else if (existsSync(join(cwd, 'yarn.lock'))) pm = 'yarn';
    else if (existsSync(join(cwd, 'bun.lock')) || existsSync(join(cwd, 'bun.lockb'))) pm = 'bun';
  }
  return pm === 'pnpm' ? 'pnpm' : pm === 'yarn' ? 'yarn' : pm === 'bun' ? 'bun run' : 'npm run';
}

function main(cwd = process.cwd()) {
  const runCmd = detectRunCmd(cwd);
  let healthJson, deadJson, dupesJson;
  try {
    healthJson = runFallow(['health']);
    deadJson = runFallow(['dead-code']);
    dupesJson = runFallow(['dupes']);
  } catch (e) {
    console.error(`Quality report incomplete — ${e.message}`);
    process.exit(2);
  }
  const summaryPath = join(cwd, 'coverage', 'coverage-summary.json');
  const coverageSummary = existsSync(summaryPath) ? JSON.parse(readFileSync(summaryPath, 'utf8')) : null;
  const data = extractData({ healthJson, deadJson, dupesJson, coverageSummary });
  const { markdown, json } = buildReport(data, runCmd);
  writeFileSync(join(cwd, 'quality-report.md'), markdown);
  writeFileSync(join(cwd, 'quality-report.json'), JSON.stringify(json, null, 2) + '\n');
  console.log('Wrote quality-report.md and quality-report.json');
}

const invokedDirectly = process.argv[1] && process.argv[1].endsWith('quality-report.mjs');
if (invokedDirectly) main();
