// The sentinel written into the generated configs whose origin the engine must
// later distinguish — the ESLint config and the test-runner config (jest/vitest).
// Readers (detect's hasUnmarkedConfig, coverage's isCoverageBaselined) match it to
// tell "engine-owned" from "hand-written"; keep it in lockstep with those headers.
export const MARKER = 'Generated by project-setup';
