// scripts/tests/coverage.test.js
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { test } from 'node:test';

import { applyCoverageFloor, floorThresholds, isCoverageBaselined, markCoverageBaselined } from '../lib/coverage.mjs';
import { tmpProject } from './helpers.js';

test('isCoverageBaselined tracks a marker file, so a 0% floor still counts as baselined', () => {
  const p = tmpProject({});
  try {
    assert.equal(isCoverageBaselined(p.dir), false);
    markCoverageBaselined(p.dir);
    assert.equal(isCoverageBaselined(p.dir), true);
  } finally {
    p.cleanup();
  }
});

test('floorThresholds floors each istanbul total pct', () => {
  const summary = { total: { statements: { pct: 84.7 }, branches: { pct: 60.2 }, functions: { pct: 90 }, lines: { pct: 84.9 } } };
  assert.deepEqual(floorThresholds(summary), { statements: 84, branches: 60, functions: 90, lines: 84 });
});

test('floorThresholds coerces Istanbul "Unknown" pct to 0 (valid numeric floor, not null)', () => {
  const summary = { total: { statements: { pct: 'Unknown' }, branches: { pct: 'Unknown' }, functions: { pct: 'Unknown' }, lines: { pct: 'Unknown' } } };
  assert.deepEqual(floorThresholds(summary), { statements: 0, branches: 0, functions: 0, lines: 0 });
});

test('applyCoverageFloor rewrites OUR generated config, skips a user config', () => {
  const ours = tmpProject({
    'jest.config.mjs': '// Generated by project-setup.\nexport default { coverageThreshold: { global: {} } };\n',
    'coverage/coverage-summary.json': { total: { statements: { pct: 80 }, branches: { pct: 50 }, functions: { pct: 70 }, lines: { pct: 80 } } },
  });
  const theirs = tmpProject({
    'jest.config.mjs': 'export default { mine: true };\n',
    'coverage/coverage-summary.json': { total: { statements: { pct: 80 }, branches: { pct: 50 }, functions: { pct: 70 }, lines: { pct: 80 } } },
  });
  try {
    const r1 = applyCoverageFloor(ours.dir, 'jest');
    assert.equal(r1.updated, true);
    assert.match(readFileSync(join(ours.dir, 'jest.config.mjs'), 'utf8'), /statements: 80/);

    const r2 = applyCoverageFloor(theirs.dir, 'jest');
    assert.equal(r2.updated, false); // no marker -> left alone
    assert.equal(readFileSync(join(theirs.dir, 'jest.config.mjs'), 'utf8'), 'export default { mine: true };\n');
  } finally {
    ours.cleanup();
    theirs.cleanup();
  }
});

test('applyCoverageFloor updates only the threshold, preserving a customized marked config', () => {
  const p = tmpProject({
    'jest.config.mjs': '// Generated by project-setup.\nexport default { setupFiles: ["./setup.js"], coverageThreshold: { global: {} } };\n',
    'coverage/coverage-summary.json': { total: { statements: { pct: 80 }, branches: { pct: 50 }, functions: { pct: 70 }, lines: { pct: 80 } } },
  });
  try {
    assert.equal(applyCoverageFloor(p.dir, 'jest').updated, true);
    const out = readFileSync(join(p.dir, 'jest.config.mjs'), 'utf8');
    assert.match(out, /setupFiles: \["\.\/setup\.js"\]/); // user customization preserved
    assert.match(out, /statements: 80/); // threshold updated in place
  } finally {
    p.cleanup();
  }
});

test('applyCoverageFloor updates the vitest thresholds block in place', () => {
  const p = tmpProject({
    'vitest.config.mjs': '// Generated by project-setup.\nexport default { test: { setupFiles: ["x"], coverage: { thresholds: {} } } };\n',
    'coverage/coverage-summary.json': { total: { statements: { pct: 42 }, branches: { pct: 42 }, functions: { pct: 42 }, lines: { pct: 42 } } },
  });
  try {
    assert.equal(applyCoverageFloor(p.dir, 'vitest').updated, true);
    const out = readFileSync(join(p.dir, 'vitest.config.mjs'), 'utf8');
    assert.match(out, /setupFiles: \["x"\]/);
    assert.match(out, /lines: 42/);
  } finally {
    p.cleanup();
  }
});
